export const formStyles = {
    page: {
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "#f5f5f5",
        fontFamily: "system-ui, sans-serif",
        padding: "24px",
    },
    card: {
        background: "#fff",
        border: "1px solid #ddd",
        borderRadius: "8px",
        padding: "40px 36px",
        width: "100%",
        maxWidth: "440px",
    },
    title: {
        margin: "0 0 4px",
        fontSize: "22px",
        fontWeight: "700",
        color: "#111",
    },
    sub: {
        margin: "0 0 28px",
        fontSize: "14px",
        color: "#666",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: "16px",
    },
    row: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "12px",
    },
    field: {
        display: "flex",
        flexDirection: "column",
        gap: "6px",
    },
    label: {
        fontSize: "13px",
        fontWeight: "600",
        color: "#333",
    },
    input: {
        padding: "10px 12px",
        border: "1px solid #ccc",
        borderRadius: "6px",
        fontSize: "14px",
        outline: "none",
        background: "#fff",
        color: "#111",
    },
    fieldError: {
        fontSize: "12px",
        color: "#dc2626",
    },
    error: {
        margin: 0,
        color: "#dc2626",
        fontSize: "13px",
        background: "#fef2f2",
        border: "1px solid #fca5a5",
        borderRadius: "6px",
        padding: "10px 12px",
    },
    btn: {
        padding: "11px",
        background: "#2563eb",
        color: "#fff",
        border: "none",
        borderRadius: "6px",
        fontSize: "15px",
        fontWeight: "600",
        cursor: "pointer",
    },
    footer: {
        marginTop: "20px",
        textAlign: "center",
        fontSize: "13px",
        color: "#666",
    },
    link: {
        color: "#2563eb",
        textDecoration: "none",
        fontWeight: "600",
    },
    idBox: {
        background: "#f0fdf4",
        border: "1px solid #86efac",
        borderRadius: "6px",
        padding: "16px",
        marginBottom: "20px",
    },
    idLabel: {
        margin: "0 0 6px",
        fontSize: "12px",
        color: "#166534",
        fontWeight: "600",
        textTransform: "uppercase",
    },
    idValue: {
        margin: 0,
        fontSize: "20px",
        fontWeight: "800",
        color: "#16a34a",
        letterSpacing: "2px",
        fontFamily: "monospace",
    },
    successTitle: {
        margin: "0 0 4px",
        fontSize: "22px",
        fontWeight: "700",
        color: "#16a34a",
    },
    divider: {
        display: "flex",
        alignItems: "center",
        textAlign: "center",
        margin: "20px 0",
        color: "#999",
        fontSize: "13px",
        gap: "12px",
    },
    dividerLine: {
        flex: 1,
        borderTop: "1px solid #e5e7eb",
    },
    socialWrapper: {
        display: "flex",
        justifyContent: "center",
    },
};
